### ISSUE TITLE
Is there any way to make prediction for just one rect?

### ISSUE THREAD

**Issue by strgrb** [joaofaro/KCFcpp#5]

**Comment by ujsyehao** [comment]
what is prediction?can you exactly describe the problem?

**Comment by strgrb** [comment]
There is no problem now. I misunderstood the part describing a correlation filter, I wanted to find a way to use the classifier to predict any one rect given by hand instead of fitering the neighboring area, which is not necessary.
Thank you very much.

**Comment by ujsyehao** [comment]
OK, can you tell me how to run the program ?should i use g++?

**Comment by strgrb** [comment]
just use cmake, there is already a CMakeLists.txt in the project.
be sure to install opencv first, there may be some include problems with different opencv version, just fix it.

**Comment by ujsyehao** [comment]
I have installed it and follow the instructions, but when I run ./KCF hog command , nothing happened, the output.txt has nothing , so if I want to have the result [https://www.youtube.com/watch?v=sZXKnPUhAi8](url), should I change the program?

**Comment by strgrb** [comment]
read src/runtracker.cpp then you will get what you want. I modified it to capture video from camera in my laptop, and I did not try the origin code.
